### ISSUE TITLE
authentification doesn't work

### ISSUE THREAD

**Issue by ghost** [MongoEngine/django-mongoengine#23]
Hi I'm started django-mongoengine and found that the authenticate function doesn't work.
Here is my registration function that actually work:

    def register(request):
        if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            try:
                user = User.objects.get(email=email)
                emailUsed = True
            except User.DoesNotExist:
                user = User(username=username, email=email)
                user.set_password(password)
                user.save()

                reussi = True
    else:
        form = UserForm()
    return render(request, 'myapp/index.html', locals())

Then I paste the login code from the doc and it doesn't work (always return invalid password):

    def connection(request):
      if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            user = authenticate(email=email, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    msg = 'you are logged !'
                else:
                    msg = 'your acount have been desactivate'
            else:
                msg = 'invalid password'
    else:
        form = LoginForm()
    return render(request, 'myapp/login.html', locals())

Here is my settings.py just in case:

    import os
    from mongoengine import *
    BASE_DIR = os.path.dirname(os.path.dirname(__file__))

    SECRET_KEY = 'g(ht#57%e&@5h=&2ge_ngzz66ji#m%d6q=ziwztnezimwjs--j'

    DEBUG = True

    TEMPLATE_DEBUG = True

    ALLOWED_HOSTS = []

    INSTALLED_APPS = (
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'mongoengine.django.mongo_auth',
        'myapp',
    )

    AUTH_USER_MODEL = 'mongo_auth.MongoUser'
    MONGOENGINE_USER_DOCUMENT = 'mongoengine.django.auth.User'

    MIDDLEWARE_CLASSES = (
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
    )

    ROOT_URLCONF = 'blog.urls'

    WSGI_APPLICATION = 'blog.wsgi.application'

    DATABASES = {
        'default': {
            'ENGINE': '',
        }
    }

    connect('tumblelog')

    SESSION_ENGINE = 'mongoengine.django.sessions'
    SESSION_SERIALIZER = 'mongoengine.django.sessions.BSONSerializer'
    AUTHENTIFICATION_BACKENDS = (
        'mongoengine.django.auth.MongoEngineBackend',
    )

    TEMPLATE_DIRS = (
        os.path.join(BASE_DIR, 'templates'),
    )

    LANGUAGE_CODE = 'en-us'

    TIME_ZONE = 'UTC'

    USE_I18N = True

    USE_L10N = True

    USE_TZ = True

    STATIC_URL = '/static/'

**Comment by garrypolley** [comment]
The example code that is stated to work does not authorize the user from what I can tell.  

The example snippet in this repo was tested against Django 1.4 and 1.5 (I think).  Can you put a debug statement in the snippet and get the local variables? `user` is coming back as `None` which would mean it's messing up in the authenticate call somehow.

**Comment by BoumTAC** [comment]
Can you put a debug statement in the snippet and get the local variables? -> How do I do that?
user is always coming back as None whatever the password is good or not.

**Comment by rozza** [comment]
Aside: This project was never stablised and released.  If you are wanting to use it and help maintain it I'll happily hand over repo access to make that happen.  Cheers, Ross

**Comment by arpitgoyalhtmedia** [comment]
Can anyone help me with running of the test cases for this application. I am trying to use pytest for the same. Is there something else I should prefer for testing?

**Comment by last-partizan** [comment]
AFAIK we don't us pytest here, we\re using nosetests and django testings tools.
I don't recommend running tests on this project, becouse many of them now is broken.
If you want, you can try runing `python setup.py test`

Try instead this manual on django testing: https://docs.djangoproject.com/en/1.8/topics/testing/overview/

**Comment by arpitgoyalhtmedia** [comment]
I have just one concern here but this is not a django project instead its a project for building django.... so I cannot use python manage.py test for the folder under tests... I will look for nosetests I haven't been working with that testing tool. Also I follow TDD approach so I would learn more with the tests about the code structure. Thank you! :+1:

**Comment by fmoro** [comment]
Authentication is working fine on my project with a custom AuthenticationMiddleware due to SESSION_KEY issue with new Options Meta class. If you want I can tell you the steps I followed to see if we can incorporate this code in django-mongoengine

**Comment by last-partizan** [comment]
Good idea. Share your steps and middleware and i try to intergrate that into django-mongoengine.

**Comment by fmoro** [comment]
Well, the only problem with authentication is when login funciton in django.contrib.auth module, try to store the SESSION_KEY with the following sentence:

```
 request.session[SESSION_KEY] = user._meta.pk.value_to_string(user)
```

In Django 1.8 the Meta class is now an Options object type, but for us object._meta is just a dictionary, so there is no pk method, and also, our pk attribute doesn't have value_to_string. And same thing happends with  _get_user_session_key function


This is the way I have solve this problem:

First of all I have created an AuthenticationMiddleware and I have switch it in MIDDLEWARE_CLASSES deleting the default django.contrib.auth.middleware.AuthenticationMiddleware.

```
MIDDLEWARE_CLASSES = (
    ...
    #'django.contrib.auth.middleware.AuthenticationMiddleware',
    'myapp.auth.AuthenticationMiddleware'
)
```

This is my auth module:

```
from django_mongoengine.auth.backends import get_user
from django.utils.functional import SimpleLazyObject

from django.contrib.auth import SESSION_KEY, BACKEND_SESSION_KEY, HASH_SESSION_KEY
from django.contrib.auth.signals import user_logged_in
from django.middleware.csrf import rotate_token

#SESSION_KEY = '_auth_user_id'

class AuthenticationMiddleware(object):
    def process_request(self, request):
        assert hasattr(request, 'session'), (
            "The Django authentication middleware requires session middleware "
            "to be installed. Edit your MIDDLEWARE_CLASSES setting to insert "
            "'django.contrib.sessions.middleware.SessionMiddleware' before "
            "'django.contrib.auth.middleware.AuthenticationMiddleware'."
        )
        request.user = SimpleLazyObject(lambda: get_user(_get_user_session_key(request)))

from bson.objectid import ObjectId
def _get_user_session_key(request):
    # This value in the session is always serialized to a string, so we need
    # to convert it back to Python whenever we access it.
    if SESSION_KEY in request.session:
        return ObjectId(request.session[SESSION_KEY])
    
def login(request, user):
    """
    Persist a user id and a backend in the request. This way a user doesn't
    have to reauthenticate on every request. Note that data set during
    the anonymous session is retained when the user logs in.
    """
    session_auth_hash = ''
    if user is None:
        user = request.user
    if hasattr(user, 'get_session_auth_hash'):
        session_auth_hash = user.get_session_auth_hash()

    if SESSION_KEY in request.session:
        if _get_user_session_key(request) != user.pk or (
                session_auth_hash and
                request.session.get(HASH_SESSION_KEY) != session_auth_hash):
            # To avoid reusing another user's session, create a new, empty
            # session if the existing session corresponds to a different
            # authenticated user.
            request.session.flush()
    else:
        request.session.cycle_key()
    try:
        request.session[SESSION_KEY] = user._meta.pk.value_to_string(user)
    except AttributeError:
        request.session[SESSION_KEY] = str(user.pk)
    request.session[BACKEND_SESSION_KEY] = user.backend
    request.session[HASH_SESSION_KEY] = session_auth_hash
    if hasattr(request, 'user'):
        request.user = user
    rotate_token(request)
    user_logged_in.send(sender=user.__class__, request=request, user=user)
```

Now we need to create a login view, since django.contrib.auth.views.login uses django.contrib.auth.login and django.contrib.auth._get_user_session_key functions. It is a shame because login view is just a copy of  django.contrib.auth.views.login, but we have to ensure that it uses our login and _get_user_session_key function.

```
from myapp.auth import login as auth_login

@sensitive_post_parameters()
@csrf_protect
@never_cache
def login(request, template_name='registration/login.html',
          redirect_field_name=REDIRECT_FIELD_NAME,
          authentication_form=AuthenticationForm,
          current_app=None, extra_context=None):
    """
    Displays the login form and handles the login action.
    """
    redirect_to = request.POST.get(redirect_field_name,
                                   request.GET.get(redirect_field_name, ''))

    if request.method == "POST":
        form = authentication_form(request, data=request.POST)
        if form.is_valid():

            # Ensure the user-originating redirection url is safe.
            if not is_safe_url(url=redirect_to, host=request.get_host()):
                redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)

            # Okay, security check complete. Log the user in.
            auth_login(request, form.get_user())

            return HttpResponseRedirect(redirect_to)
    else:
        form = authentication_form(request)

    current_site = get_current_site(request)

    context = {
        'form': form,
        redirect_field_name: redirect_to,
        'site': current_site,
        'site_name': current_site.name,
    }
    if extra_context is not None:
        context.update(extra_context)

    if current_app is not None:
        request.current_app = current_app

    return TemplateResponse(request, template_name, context)
```

The last step to do is just use this view as login view:

```
urlpatterns = patterns('',
    url(r'^login/$', 'myapp.views.login', {'template_name': 'my_custom_template.html', 'current_app': 'myappl', 'authentication_form': MyAuthenticationForm}, name='login'),
    ...
)
```

I think that we could incorporate the autentication middleware and the login view controller on the auth package...

**Comment by last-partizan** [comment]
I fixed it in a somewhat tricky way.

If django auth wants `User._meta.pk.value_to_string` - i just added this.

**Comment by maria** [comment]
@last-partizan for me it didn't work. I still get the error. Am I missing something? Thanks in advanced.

**Comment by last-partizan** [comment]
@maria are you installed django-mongoengine from git?

**Comment by maria** [comment]
Yes, I forked the repo and install via pip with my URL repo.

**Comment by last-partizan** [comment]
So, what error do you get? last time i checked this using example app, and it was working.

**Comment by maria** [comment]
This is what I get when I try to create a session / login with my user (the model is defined using django-
![screenshot 2015-11-26 12 26 35](https://cloud.githubusercontent.com/assets/1681405/11420778/03bfb366-9439-11e5-9d35-87700594313d.png)
mongoengine)

**Comment by last-partizan** [comment]
I don't see exact error. try copy-pasting ettire traceback.

**Comment by maria** [comment]
```

**Comment by last-partizan** [comment]
Check your settings, there must be something like this:
```
AUTH_USER_MODEL = 'mongo_auth.MongoUser'

AUTHENTICATION_BACKENDS = (
    'django_mongoengine.mongo_auth.backends.MongoEngineBackend',
)
```

And i just checked example app, it's working. Try to look at the example app code and figure out why it doesn't work for you.

**Comment by maria** [comment]
OK thank you, will do.
